### YamlMime:YamlDocument
documentType: LandingData
title: Ansible in Azure Documentation
metadata:
  title: Ansible in Azure Documentation - Tutorials, samples, reference, and resources
  meta.description: Learn how to use Ansible to automate cloud provisioning, configuration management, and application deployments.
  services: terraform
  author: tomarcher
  manager: routlaw
  ms.service: ansible
  ms.tgt_pltfrm: na
  ms.devlang: devops
  ms.topic: landing-page
  ms.date: 07/05/2018
  ms.author: tarcher
abstract:
  description: Use <a href="http://www.ansible.com">Ansible</a> to automate cloud provisioning, configuration management, and application deployments.
sections:
sections:
- title: 5-Minute Quickstarts
  items: 
  - type: paragraph
    text: Configure Ansible and use it to create a Linux VM in Azure.
  - type: list
    style: icon48
    items: 
    - image: 
        src: /azure/media/index/azure_dev-9.svg
      text: Configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
    - image: 
        src: /azure/media/index/VirtualMachine.svg
      text: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json
- title: Step-by-Step Tutorials
  items:
  - type: paragraph
    text: Learn how to use Ansible to create and manage Azure compute and networking infrastructure.
  - type: list
    style: unordered
    items:
    - html: <a href="/azure/virtual-machines/linux/ansible-create-complete-vm?toc=%2Fen-us%2Fazure%2Fansible%2Ftoc.json&bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json">Create a Linux virtual machine, including virtual network, public IP address, and virtual network interface card.</a>
    - html: <a href="./ansible-run-playbook-in-cloudshell">Connect to an Azure virtual machine and run an Ansible playbook in Cloud Shell.</a>
    - html: <a href="./ansible-manage-azure-dynamic-inventories">Create and manage a dynamic inventory of your Azure resourcese.</a>
- title: Reference
  items:
  - type: list
    style: cards
    className: cardsD
    items:
    - title: Playbook roles
      html: <p><a href="https://galaxy.ansible.com/Azure/azure_preview_modules/">azure_preview_module</a></p>
    - title: Releases and features
      html: <p><a href="./ansible-matrix.md">Features matrix for modules and roles</a></p>
    - title: Tools
      html: <p><a href="https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible">Visual Studio Code extension for Ansible</a></p>