- name: Ansible in Azure
  href: ./index.yml
- name: Overview
  items:
  - name: About Ansible in Azure
    href: ./ansible-overview.md
- name: Quickstarts
  expanded: true
  items:
    - name: Install and configure Ansible
      href: /azure/virtual-machines/linux/ansible-install-configure
      maintainContext: true
    - name: Create a Linux VM
      href: /azure/virtual-machines/linux/ansible-create-vm
      maintainContext: true
- name: Tutorials 
  items:
  - name: Create a complete Linux VM
    href: /azure/virtual-machines/linux/ansible-create-complete-vm
    maintainContext: true
  - name: Run a playbook in Cloud Shell
    href: ./ansible-run-playbook-in-cloudshell.md
    maintainContext: true
  - name: Manage dynamic inventories
    href: ./ansible-manage-azure-dynamic-inventories.md
    maintainContext: true
- name: Reference
  items:
  - name: Playbook roles
    items:
    - name: azure_module
      href: https://galaxy.ansible.com/Azure/azure_modules/
    - name: azure_preview_module
      href: https://galaxy.ansible.com/Azure/azure_preview_modules
  - name: Releases and features
    href: ./ansible-matrix.md  
  - name: Azure Container Instances
    href: http://docs.ansible.com/ansible/latest/azure_rm_containerinstance_module.html
  - name: Azure Functions
    href: http://docs.ansible.com/ansible/latest/azure_rm_functionapp_module.html
  - name: Load balancers
    href: http://docs.ansible.com/ansible/latest/azure_rm_loadbalancer_module.html
  - name: Virtual machines
    href: http://docs.ansible.com/ansible/latest/azure_rm_virtualmachine_module.html
  - name: All modules for Azure
    href: http://docs.ansible.com/ansible/latest/list_of_cloud_modules.html#azure
- name: Tools
  items:
  - name: Visual Studio Code extension for Ansible
    href: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible